---
- name: openstack.ansible
  src: git+https://git.openstack.org/openstack/ansible-role-ansible

- name: openstack.sudoers
  src: git+https://git.openstack.org/openstack/ansible-role-sudoers

- name: openstack.virtualenv
  src: git+https://git.openstack.org/openstack/ansible-role-virtualenv
